server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/melurodriguez/service-configuration.git
          default-label: main
          clone-on-start: true
          search-paths: config-data